# Generated by Django 4.0 on 2021-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_data_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('genres', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=3000)),
            ],
        ),
    ]
