# Generated by Django 4.0 on 2021-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_data_list',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('genres', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_review',
            fields=[
                ('movie_id', models.IntegerField(default=0)),
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=10000)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
