# Generated by Django 4.0 on 2021-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
