# Generated by Django 4.0 on 2021-12-12 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_info', '0002_alter_movie_review_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_review',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_info.movie_data_list'),
        ),
    ]
