# Generated by Django 4.0 on 2021-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_info', '0003_alter_movie_review_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data_list',
            name='genres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie_data_list',
            name='summary',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='movie_data_list',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie_review',
            name='text',
            field=models.CharField(max_length=1500),
        ),
    ]
